# -- Milvus Configurations
milvus:
    host: localhost
    port: 19530
    collection_name: my_rag_collection
    search:
        limit: 5
        metric_type: IP

# -- Model Configurations
model:
    platform: google    # openai | google | ollama
    embedding_model: models/embedding-001
    chat_model: gemini-pro
