# -- Milvus Configurations
milvus:
    host: localhost
    port: 19530
    collection_name: multimodal_rag
    search:
        limit: 9
        metric_type: COSINE

# -- Model Configurations
model:
    platform: openai    # openai | google | ollama
    embedding_model: text-embedding-3-small
    chat_model: gpt-3.5-turbo
